cmake_minimum_required(VERSION 3.20)

project(cuda_career_180)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(hello hello.cpp)

add_executable(test test.cpp)

add_executable(type type.cpp)

add_executable(if1 if1.cpp)

add_executable(plus plus.cpp)

add_executable(new new.cpp)